spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inspire?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    passoword: sdf
    hikari:
      minimumIdle: 1
      maxPoolSize: 10
      idleTimeout: 60000
datasource:
  config:
    connections:
      - name: inspire
        username: root
        password:
        url: jdbc:mysql://localhost:3306/inspire?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8